コメントを付けられるようにするの課題
tomoyuki2022/fjord-books_app-2023 pull request #5
Opened 2024-02-01 07:14 UTC by tomoyuki2022

コメントを付けられるようにするの課題を提出しました。
ご確認お願いします。

2024-02-07 16:28 UTC, u1tnk requested changes

2024-02-07 16:28 UTC, u1tnk commented on app/controllers/comments_controller.rb
> +    @comment.destroy
基本的に成功するパターンはifは不要ですが、その替わりに`destroy!`にしましょう。
バグなので更新できないときにすぐ気づけるので。

2024-02-07 16:28 UTC, u1tnk commented on app/controllers/reports_controller.rb
> +    @report.destroy
こちらも同様です。

2024-02-07 16:32 UTC, u1tnk requested changes

2024-02-07 16:32 UTC, u1tnk commented on app/controllers/reports_controller.rb
> +      if @report.update(report_params)
このreportは  他ユーザのものも更新できそうに見えますがどうでしょうか？

2024-02-07 16:32 UTC, u1tnk commented on app/controllers/reports_controller.rb
> +    @report.destroy
同じく他ユーザのものが消せそうです。

2024-02-08 06:45 UTC, tomoyuki2022 commented
修正しましたのでご確認お願いします🙇‍♂️

2024-02-08 16:06 UTC, u1tnk requested changes

2024-02-08 16:06 UTC, u1tnk commented on app/controllers/reports_controller.rb
> +  def set_report
ここを見て、他ユーザでも update/destroyできるんじゃないか？という指摘をしたんですが、それぞれの上書きしてるんですね。
とはいえ、ここは 全部のメソッドで呼んでいるようなので、冗長なのと僕みたいに勘違いする事がありそうですね。

before_actionの対象を showだけにすれば良いんですが、それだったらメソッド無くしても良いかも？
もしくは  `current_user.reports.find(params[:id])` を別のメソッドにして使い分けるとか。
ユーザ制限あり/なし版を一貫性のある方法で使い方を揃えて欲しいです。

2024-02-09 01:10 UTC, tomoyuki2022 commented on app/controllers/reports_controller.rb
> +  def set_report
>ここを見て、他ユーザでも update/destroyできるんじゃないか？という指摘をしたんですが、それぞれの上書きしてるんですね。
とはいえ、ここは 全部のメソッドで呼んでいるようなので、冗長なのと僕みたいに勘違いする事がありそうですね。

set_reportだったんですね。理解できていませんでした。すいません。

>before_actionの対象を showだけにすれば良いんですが、それだったらメソッド無くしても良いかも？
もしくは current_user.reports.find(params[:id]) を別のメソッドにして使い分けるとか。
ユーザ制限あり/なし版を一貫性のある方法で使い方を揃えて欲しいです。

修正します🙇‍♂️

2024-02-09 03:16 UTC, tomoyuki2022 commented
修正しましたのでご確認お願いします。

2024-02-09 14:48 UTC, u1tnk requested changes

2024-02-09 14:48 UTC, u1tnk commented on app/controllers/reports_controller.rb
> +  def set_report
いえいえ僕も最初ちょっと勘違いしていたところもありますし、分かりづらかったかなと思います。

2024-02-09 14:48 UTC, u1tnk commented on app/controllers/reports_controller.rb
> +  def current_user_report
ほぼオッケーなんですが、 set_reportと並列にするなら setを付けて欲しいです 🙏

2024-02-13 02:23 UTC, tomoyuki2022 commented
修正しましたのでご確認お願いします。

2024-02-13 13:09 UTC, u1tnk approved these changes

2024-02-16 00:49 UTC, merged